GET  http://127.0.0.1:5001/users


###
POST http://127.0.0.1:5001/users 
Content-Type:  application/json

{
    "name":"Wiseman",
    "password": "password"
}

###
POST http://127.0.0.1:5001/members/login
Content-Type:  application/json

{
    "firstname":"Kulani",
    "password": "lulama"
}